stages:
  - deploy

variables:
  NODE_VERSION: "18"

deploy:
  stage: deploy
  image: node:${NODE_VERSION}
  script:
    - npm ci
    - echo "CLOUDFLARE_API_TOKEN=$CLOUDFLARE_API_TOKEN" > .env
    - npx wrangler deploy
  environment:
    name: production
    url: https://${CI_PROJECT_NAME}.${CLOUDFLARE_WORKERS_DOMAIN}
  only:
    - main
