name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      NODE_VERSION: 20
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build Next.js app
        run: npm run build
        
      - name: Setup Cloudflare API token
        run: echo "CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }}" > .env
        
      - name: Deploy to Cloudflare Workers
        run: npx wrangler deploy
        
      - name: Output deployment URL
        run: echo "Deployed to https://${{ github.event.repository.name }}.${{ secrets.CLOUDFLARE_WORKERS_DOMAIN }}"
